<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('books')->insert(
            [
                // Suzanne Collins
                [
                    'author_id' => 1,
                    'title' => "Gregor the Overlander",
                    'isbn' => "9780439678131",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 1,
                    'title' => "Gregor and the Prophecy of Bane",
                    'isbn' => "9780439650762",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 1,
                    'title' => "Gregor and the Curse of the Warmbloods",
                    'isbn' => "9780439656245",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 1,
                    'title' => "Gregor and the Marks of Secret",
                    'isbn' => "9780439791465",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 1,
                    'title' => "Gregor and the Code of Claw",
                    'isbn' => "9780439791441",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 1,
                    'title' => "The Hunger Games",
                    'isbn' => "9780439023528",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 1,
                    'title' => "Catching Fire",
                    'isbn' => "9780545227247",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 1,
                    'title' => "Mockingjay",
                    'isbn' => "9780439023511",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                // Anne McCaffrey
                [
                    'author_id' => 2,
                    'title' => "Dragonflight",
                    'isbn' => "9780345335463",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 2,
                    'title' => "Dragonquest",
                    'isbn' => "9780345022455",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 2,
                    'title' => "The White Dragon",
                    'isbn' => "9780345275677",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 2,
                    'title' => "Dragonsong",
                    'isbn' => "9780689305078",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 2,
                    'title' => "Dragonsinger",
                    'isbn' => "9780689305702",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 2,
                    'title' => "Dragondrums",
                    'isbn' => "9780689306853",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                // Peter F. Hamilton
                [
                    'author_id' => 3,
                    'title' => "Mindstar Rising",
                    'isbn' => "9780330537742",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "A Quantum Murder",
                    'isbn' => "9780330537759",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Nano Flower",
                    'isbn' => "9780330537810",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Reality Dysfunction",
                    'isbn' => "9781447208570",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Neutronium Alchemist",
                    'isbn' => "9781447208587",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Naked God",
                    'isbn' => "9781447208594",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "Misspent Youth",
                    'isbn' => "9781447224082",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "Pandora's Star",
                    'isbn' => "9781447279662",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "Judas Unchained",
                    'isbn' => "9781447279679",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Dreaming Void",
                    'isbn' => "9781447208563",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Temporal Void",
                    'isbn' => "9780330507882",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Evolutionary Void",
                    'isbn' => "9780330443173",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 3,
                    'title' => "The Abyss Beyond Dreams",
                    'isbn' => "9780230769465",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                // J. K. Rowling
                [
                    'author_id' => 4,
                    'title' => "Harry Potter and the Philosopher's Stone",
                    'isbn' => "0747532699",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 4,
                    'title' => "Harry Potter and the Chamber of Secrets",
                    'isbn' => "0747538492",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 4,
                    'title' => "Harry Potter and the Prisoner of Azkaban",
                    'isbn' => "0747542155",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 4,
                    'title' => "Harry Potter and the Goblet of Fire",
                    'isbn' => "074754624X",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 4,
                    'title' => "Harry Potter and the Order of the Phoenix",
                    'isbn' => "0747551006",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 4,
                    'title' => "Harry Potter and the Half-Blood Prince",
                    'isbn' => "0747581088",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 4,
                    'title' => "Harry Potter and the Deathly Hallows",
                    'isbn' => "0545010225",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                // Ursula Le Guin
                [
                    'author_id' => 5,
                    'title' => "A Wizard of Earthsea",
                    'isbn' => "0395276535",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Tombs of Atuan",
                    'isbn' => "187470323X",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Farthest Shore",
                    'isbn' => "0689300549",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "Tehanu",
                    'isbn' => "0689315953",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "Tales from Earthsea",
                    'isbn' => "0151005613",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Other Wind",
                    'isbn' => "0151006849",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Dispossessed",
                    'isbn' => "0060125632",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Word for World Is Forest",
                    'isbn' => "0399117164",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "Rocannon's World",
                    'isbn' => "0824014243",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "Planet of Exile",
                    'isbn' => "0575025956",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "City of Illusions",
                    'isbn' => "0575007583",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Left Hand of Darkness",
                    'isbn' => "0441478123",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Telling",
                    'isbn' => "0151005672",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Lathe of Heaven",
                    'isbn' => "0684125293",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "The Wind's Twelve Quarters",
                    'isbn' => "0060125624",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 5,
                    'title' => "Orsinian Tales",
                    'isbn' => "0060125616",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                // Terry Pratchett
                [
                    'author_id' => 6,
                    'title' => "The Colour of Magic",
                    'isbn' => "086140324X",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Light Fantastic",
                    'isbn' => "0861402030",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Equal Rites",
                    'isbn' => "0575039507",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Mort",
                    'isbn' => "0575041714",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Sourcery",
                    'isbn' => "0575042176",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Wyrd Sisters",
                    'isbn' => "0575043636",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Pyramids",
                    'isbn' => "0575044632",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Guards! Guards!",
                    'isbn' => "0575046066",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Eric",
                    'isbn' => "0575051914",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Moving Pictures",
                    'isbn' => "0575047631",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Reaper Man",
                    'isbn' => "0575049790",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Witches Abroad",
                    'isbn' => "0575049804",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Small Gods",
                    'isbn' => "0060177500",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Lords and Ladies",
                    'isbn' => "0575052236",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Men At Arms",
                    'isbn' => "0575055030",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Soul Music",
                    'isbn' => "0575055049",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Interesting Times",
                    'isbn' => "0575058005",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Maskerade",
                    'isbn' => "0575058080",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Feet of Clay",
                    'isbn' => "0575059001",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Hogfather",
                    'isbn' => "057506403X",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Jingo",
                    'isbn' => "0575065400",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Last Continent",
                    'isbn' => "0385409893",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Carpe Jugulum",
                    'isbn' => "0385409923",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Fifth Elephant",
                    'isbn' => "0385409958",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Truth",
                    'isbn' => "0385601026",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Thief of Time",
                    'isbn' => "0060199563",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Last Hero",
                    'isbn' => "057506885X",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Amazing Murice and his Educated Rodents",
                    'isbn' => "0385601239",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Night Watch",
                    'isbn' => "0385602642",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Wee Free Men",
                    'isbn' => "0385605331",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Monstrous Regiment",
                    'isbn' => "0385603401",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "A Hat Full of Sky",
                    'isbn' => "0385607369",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Going Postal",
                    'isbn' => "0385603428",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Thud!",
                    'isbn' => "0385608675",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Wintersmith",
                    'isbn' => "0385609841",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Making Money",
                    'isbn' => "0385611013",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Unseen Academicals",
                    'isbn' => "0385609345",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "I Shall Wear Midnight",
                    'isbn' => "0385611072",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Snuff",
                    'isbn' => "9780385619264",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "Raising Steam",
                    'isbn' => "9780857522276",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'author_id' => 6,
                    'title' => "The Shepherd's Crown",
                    'isbn' => "9780857534811",
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
            ]
        );
    }
}
